WebbySoftware/Controllers/DeskController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using WebbySoftware.Application.DeskOperations.Commands.CreateDesk;
using WebbySoftware.Application.DeskOperations.Commands.DeleteDesk;
using WebbySoftware.Application.DeskOperations.Commands.UpdateDesk;
using WebbySoftware.Application.DeskOperations.Queries;
using WebbySoftware.DBOperations;
using FluentValidation;
using WebbySoftware.Models;
namespace WebbySoftware.Controllers.DeskController
{
    public class DeskController: Controller
    {
        private readonly IWebbySoftDBContext _context;
        private readonly IMapper _mapper;

        public DeskController(IWebbySoftDBContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        [HttpGet("Development/DesktopDevelopment")]
        public IActionResult DesktopDevelopment(string? searchedTag)
        {
            GetDeskQuery query = new GetDeskQuery(_context, _mapper);
            var result = string.IsNullOrEmpty(searchedTag) ? query.Handle() : query.Handle(searchedTag);
            return View("~/Views/Development/DesktopDevelopment.cshtml", result);
        }

        [HttpGet("Development/DesktopDevelopment/[action]")]
        public IActionResult GetDeskQuery(string? searchedTag)
        {
            GetDeskQuery query = new GetDeskQuery(_context, _mapper);
            var result = string.IsNullOrEmpty(searchedTag) ? query.Handle() : query.Handle(searchedTag);
            return Ok(result);
        }


        [HttpGet("Development/DesktopDevelopment/[action]/{id}")]
        public IActionResult GetDeskById(int id)
        {
            GetDeskById query = new GetDeskById(_context,_mapper);
            DeskDevIdModel result;
            query.DeskID = id;
            GetDeskByIdValidator validator = new GetDeskByIdValidator();
            validator.ValidateAndThrow(query);
            result = query.Handle();
            return Ok(result);
        }

        [HttpPost("Development/DesktopDevelopment/[action]")]
        public IActionResult CreateDesktopApp([FromBody] DeskDevModel newDesk)
        {
            CreateDeskCommand command = new CreateDeskCommand(_context,_mapper);
            command.Model = newDesk;
            CreateDeskCommandValidator validator = new CreateDeskCommandValidator();
            validator.ValidateAndThrow(command);
            command.Handle();
            return Ok();
        }

        [HttpPut("Development/DesktopDevelopment/[action]/{id}")]
        public IActionResult UpdateDesktopApp(int id,[FromBody] UpdateDeskModel updateDesk)
        {
            UpdateDeskCommand command = new UpdateDeskCommand(_context,_mapper);

            command.DeskID = id;
            command.Model = updateDesk;
            UpdateDeskCommandValidator validator = new UpdateDeskCommandValidator();
            validator.ValidateAndThrow(command);
            command.Handle(); 
            return Ok();
        }

        [HttpDelete("Development/DesktopDevelopment/[action]/{id}")]
        public IActionResult DeleteDesktopApp(int id)
        {
            DeleteDeskCommand command = new DeleteDeskCommand(_context);
            command.DeskID=id;
            DeleteDeskCommandValidator validator = new DeleteDeskCommandValidator();
            validator.ValidateAndThrow(command);
            command.Handle();
            return Ok();
        }
    }
}

WebbySoftware/Controllers/GameController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using WebbySoftware.Application.GameOperations.Commands.CreateGame;
using WebbySoftware.Application.GameOperations.Commands.DeleteGame;
using WebbySoftware.Application.GameOperations.Commands.UpdateGame;
using WebbySoftware.Application.GameOperations.Queries;
using WebbySoftware.DBOperations;
using FluentValidation;
using WebbySoftware.Models;

namespace WebbySoftware.Controllers.GameController;

public class GameController : Controller
{
    private readonly IWebbySoftDBContext _context;
    private readonly IMapper _mapper;

    public GameController(IWebbySoftDBContext context, IMapper mapper)
    {
        _context = context;
        _mapper = mapper;
    }

    [HttpGet("Development/GameDevelopment")]
    public IActionResult GameDevelopment(string? searchedTag)
    {
        GetGameQuery query = new GetGameQuery(_context, _mapper);
        var result = string.IsNullOrEmpty(searchedTag) ? query.Handle() : query.Handle(searchedTag);
        return View("~/Views/Development/GameDevelopment.cshtml", result);
    }

    [HttpGet("Development/GameDevelopment/[action]")]
    public IActionResult GetGameQuery(string? searchedTag)
    {
        GetGameQuery query = new GetGameQuery(_context, _mapper);
        var result = string.IsNullOrEmpty(searchedTag) ? query.Handle() : query.Handle(searchedTag);
        return Ok(result);
    }


    [HttpGet("Development/GameDevelopment/[action]/{id}")]
    public IActionResult GetGameById(int id)
    {
        GetGameByID query = new GetGameByID(_context,_mapper);
        GameDevIdModel result;
        query.GameID = id;
        GetGameByIdValidator validator = new GetGameByIdValidator();
        validator.ValidateAndThrow(query);
        result = query.Handle();
        return Ok(result);
    }

    [HttpPost("Development/GameDevelopment/[action]")]
    public IActionResult CreateGame([FromBody] GameDevModel newGame)
    {
        CreateGameCommand command = new CreateGameCommand(_context,_mapper);
        command.Model = newGame;
        CreateGameCommandValidator validator = new CreateGameCommandValidator();
        validator.ValidateAndThrow(command);
        command.Handle();
        return Ok();
    }

    [HttpPut("Development/GameDevelopment/[action]/{id}")]
    public IActionResult UpdateGame(int id,[FromBody] UpdateGameModel updateGame)
    {
        UpdateGameCommand command = new UpdateGameCommand(_context,_mapper);

        command.GameID = id;
        command.Model = updateGame;
        UpdateGameCommandValidator validator = new UpdateGameCommandValidator();
        validator.ValidateAndThrow(command);
        command.Handle(); 
        return Ok();
    }

    [HttpDelete("Development/GameDevelopment/[action]/{id}")]
    public IActionResult DeleteGame(int id)
    {
        DeleteGameCommand command = new DeleteGameCommand(_context);
        command.GameID=id;
        DeleteGameCommandValidator validator = new DeleteGameCommandValidator();
        validator.ValidateAndThrow(command);
        command.Handle();
        return Ok();
    }
}

WebbySoftware/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.OpenApi.Models;
using System.Diagnostics;
using WebbySoftware.Application.DevOperations.Queries;
using WebbySoftware.Application.GameOperations.Queries;
using WebbySoftware.Application.MobileAppOperations.Queries;
using WebbySoftware.Application.UserOperations.Queries;
using WebbySoftware.Application.WebOperations.Queries;
using WebbySoftware.DBOperations;
using WebbySoftware.Models;

namespace WebbySoftware.Controllers
{
	public class HomeController : Controller
	{

		private readonly IWebbySoftDBContext _context;
		private readonly IMapper _mapper;

		public HomeController(IWebbySoftDBContext context, IMapper mapper)
		{
			_context = context;
			_mapper = mapper;
		}
		
		[HttpGet("")]
		public IActionResult Home()
		{
			GetAllDevelopmentTitles query = new GetAllDevelopmentTitles(_context, _mapper);
			var result = query.Handle();
			return View("Home", result);
		}

		[HttpGet("About")]
		public IActionResult About()
		{
			return View();
		}

		[HttpGet("Team")]
		public IActionResult Team()
		{
			GetUserQuery query = new GetUserQuery(_context, _mapper);
			var result = query.Handle();
			return View(result);
		}

		[HttpGet("Contact")]
		public IActionResult Contact()
		{
			GetUserQuery query = new GetUserQuery(_context, _mapper);
			var result = query.Handle();
			return View(result);
		}

	}
}

WebbySoftware/Controllers/MobileController.cs
using AutoMapper;
using WebbySoftware.Application.MobileAppOperations.Commands.CreateMobileApp;
using WebbySoftware.Application.MobileAppOperations.Commands.DeleteMobileApp;
using WebbySoftware.Application.MobileAppOperations.Commands.UpdateMobileApp;
using WebbySoftware.Application.MobileAppOperations.Queries;
using WebbySoftware.DBOperations;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;
using WebbySoftware.Models;

namespace WebbySoftware.Controllers.MobileAppController;

public class MobileAppController : Controller
{
    private readonly IWebbySoftDBContext _context;
    private readonly IMapper _mapper;

    public MobileAppController(IWebbySoftDBContext context, IMapper mapper)
    {
        _context = context;
        _mapper = mapper;
    }

    [HttpGet("Development/MobileAppDevelopment")]
    public IActionResult MobileAppDevelopment(string? searchedTag)
    {
        GetMobileAppQuery query = new GetMobileAppQuery(_context, _mapper);
        var result = string.IsNullOrEmpty(searchedTag) ? query.Handle() : query.Handle(searchedTag);
        return View("~/Views/Development/MobileAppDevelopment.cshtml", result);
    }

    [HttpGet("Development/MobileAppDevelopment/[action]")]
    public IActionResult GetMobileAppQuery(string? searchedTag)
    {
        GetMobileAppQuery query = new GetMobileAppQuery(_context, _mapper);
        var result = string.IsNullOrEmpty(searchedTag) ? query.Handle() : query.Handle(searchedTag);
        return Ok(result);
    }

    [HttpGet("Development/MobileAppDevelopment/[action]/{id}")]
    public IActionResult GetMobileAppById(int id)
    {
        GetMobileAppByID query = new GetMobileAppByID(_context,_mapper);
        MobileAppIdModel result;
        query.MobileAppID = id;
        GetMobileAppByIdValidator validator = new GetMobileAppByIdValidator();
        validator.ValidateAndThrow(query);
        result = query.Handle();
        return Ok(result);
    }

    [HttpPost("Development/MobileAppDevelopment/[action]")]
    public IActionResult CreateMobileApp([FromBody] MobileAppDevModel newMobileApp)
    {
        CreateMobileAppCommand command = new CreateMobileAppCommand(_context,_mapper);
        command.Model = newMobileApp;
        CreateMobileAppCommandValidator validator = new CreateMobileAppCommandValidator();
        validator.ValidateAndThrow(command);
        command.Handle();
        return Ok();
    }

    [HttpPut("Development/MobileAppDevelopment/[action]/{id}")]
    public IActionResult UpdateMobileApp(int id,[FromBody] UpdateMobileAppModel updateMobileApp)
    {
        UpdateMobileAppCommand command = new UpdateMobileAppCommand(_context,_mapper);

        command.MobileAppID = id;
        command.Model = updateMobileApp;
        UpdateMobileAppCommandValidator validator = new UpdateMobileAppCommandValidator();
        validator.ValidateAndThrow(command);
        command.Handle(); 
        return Ok();
    }

    [HttpDelete("Development/MobileAppDevelopment/[action]/{id}")]
    public IActionResult DeleteMobileApp(int id)
    {
        DeleteMobileAppCommand command = new DeleteMobileAppCommand(_context);
        command.MobileAppID=id;
        DeleteMobileAppCommandValidator validator = new DeleteMobileAppCommandValidator();
        validator.ValidateAndThrow(command);
        command.Handle();
        return Ok();
    }
}

WebbySoftware/Controllers/WebController.cs
using AutoMapper;
using WebbySoftware.Application.WebOperations.Commands.CreateWebApp;
using WebbySoftware.Application.WebOperations.Commands.DeleteWeb;
using WebbySoftware.Application.WebOperations.Commands.UpdateWebApp;
using WebbySoftware.Application.WebOperations.Queries;
using WebbySoftware.DBOperations;
using FluentValidation;
using Microsoft.AspNetCore.Mvc;

namespace WebbySoftware.Controllers.WebController;

public class WebController : Controller
{
    private readonly IWebbySoftDBContext _context;
    private readonly IMapper _mapper;

    public WebController(IWebbySoftDBContext context, IMapper mapper)
    {
        _context = context;
        _mapper = mapper;
    }

    [HttpGet("Development/WebDevelopment")]
    public IActionResult WebDevelopment(string? searchedTag)
    {
        GetWebQuery query = new GetWebQuery(_context, _mapper);
        var result = string.IsNullOrEmpty(searchedTag) ? query.Handle() : query.Handle(searchedTag);
        return View("~/Views/Development/WebDevelopment.cshtml", result);
    }

    [HttpGet("Development/WebDevelopment/[action]")]
    public IActionResult GetWebQuery(string? searchedTag)
    {
        GetWebQuery query = new GetWebQuery(_context, _mapper);
        var result = string.IsNullOrEmpty(searchedTag) ? query.Handle() : query.Handle(searchedTag);
        return Ok(result);
    }

    [HttpGet("Development/WebDevelopment/[action]/{id}")]
    public IActionResult GetWebById(int id)
    {
        GetWebByID query = new GetWebByID(_context,_mapper);
        GetWebByIDModel result;
        query.WebAppID = id;
        GetWebByIdValidator validator = new GetWebByIdValidator();
        validator.ValidateAndThrow(query);
        result = query.Handle();
        return Ok(result);
    }

    [HttpPost("Development/WebDevelopment/[action]")]
    public IActionResult CreateWeb([FromBody] WebDevModel newWeb)
    {
        CreateWebAppCommand command = new CreateWebAppCommand(_context,_mapper);
        command.Model = newWeb;
        CreateWebAppCommandValidator validator = new CreateWebAppCommandValidator();
        validator.ValidateAndThrow(command);
        command.Handle();
        return Ok();
    }

    [HttpPut("Development/WebDevelopment/[action]/{id}")]
    public IActionResult UpdateWeb(int id,[FromBody] UpdateWebAppModel updateWeb)
    {
        UpdateWebAppCommand command = new UpdateWebAppCommand (_context,_mapper);

        command.WebAppID = id;
        command.Model = updateWeb;
        UpdateWebAppCommandValidator validator = new UpdateWebAppCommandValidator();
        validator.ValidateAndThrow(command);
        command.Handle(); 
        return Ok();
    }

    [HttpDelete("Development/WebDevelopment/[action]/{id}")]
    public IActionResult DeleteWeb(int id)
    {
        DeleteWebAppCommand command = new DeleteWebAppCommand(_context);
        command.WebAppID=id;
        DeleteWebAppCommandValidator validator = new DeleteWebAppCommandValidator();
        validator.ValidateAndThrow(command);
        command.Handle();
        return Ok();
    }
}

WebbySoftware/Views/Home/Contact.cshtml
<section id="contact" class="contact section-bg">
    <div class="container">

        <div class="section-title" data-aos="fade-up">
            <h2>Contact Us</h2>
        </div>

        <div class="row">
            <div class="col-lg-5 d-flex flex-column align-items-stretch" data-aos="fade-right">
                @if (Model != null && Model.Count > 0)
                {
                    <hr/>
                    foreach (var user in Model)
                    {
                        <div class="user-info my-3">
                            <h4>@user.Name @user.Surname:</h4>
                            <div class="email d-flex align-items-center mb-2">
                                <i class="bi bi-envelope"></i>
                                <p style="margin-left: 5px;" class="mb-0">@user.Email</p>
                            </div>

                            <div class="phone d-flex align-items-center">
                                <i class="bi bi-phone"></i>
                                <p class="ml-10 mb-0"> @user.Phone</p>
                            </div>
                        </div>
                        <hr/>
                    }
                }
                else
                {
                    <p>No users found.</p>
                }
            </div>


            <div class="col-lg-7 mt-5 mt-lg-0 d-flex align-items-stretch" data-aos="fade-left">
                <form action="mailto:yildizhakan88@gmail.com" method="post" role="form" class="php-email-form">
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label for="name">Your Name</label>
                            <input type="text" name="name" class="form-control" id="name" required>
                        </div>
                        <div class="form-group col-md-6 mt-3 mt-md-0">
                            <label for="name">Your Email</label>
                            <input type="email" class="form-control" name="email" id="email" required>
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <label for="name">Subject</label>
                        <input type="text" class="form-control" name="subject" id="subject" required>
                    </div>
                    <div class="form-group mt-3">
                        <label for="name">Message</label>
                        <textarea class="form-control" name="message" rows="10" required></textarea>
                    </div>
                    <div class="my-3">
                        <div class="loading">Loading</div>
                        <div class="error-message"></div>
                        <div class="sent-message">Your message has been sent. Thank you!</div>
                    </div>
                    <div class="text-center"><button type="submit">Send Message</button></div>
                </form>
            </div>
        </div>

    </div>
</section>

WebbySoftware/Views/Home/Home.cshtml
@model WebbySoftware.Application.DevOperations.Queries.DevelopmentViewModel
    

@{
    ViewData["Title"] = "Home";
}

<!-- ======= Hero Section ======= -->
<section id="hero">

    <div class="container">
        <div class="row">
            <div class="col-lg-6 pt-5 pt-lg-0 order-2 order-lg-1 d-flex flex-column justify-content-center" data-aos="fade-up">
                <div>
                    <h1>Webbysoft Initiative create digital products for digital solutions.</h1>
                    <h2>We are a versatile team of like-minded friends with enthusiasm in software development. Our purpose is to create a single portfolio for a group of like-minded friends for showcasing our works and create a basis for future freelancing work.</h2>
                    <a href="#portfolio" class="btn-get-started scrollto">Check our Projects!</a>
                </div>
            </div>
            <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="fade-left">
                <img src="~/assets/img/hero-img.png" class="img-fluid" alt="">
            </div>
        </div>
    </div>

</section><!-- End Hero -->

<main id="main">

<!-- ======= Services Section ======= -->
<section id="services" class="services section-bg">
    <div class="container">

        <div class="section-title" data-aos="fade-up">
            <h2>Services</h2>
            <p>We, as WebbySoft Initiative, endeavor to offer comprehensive, customized, and cutting-edge solutions for all your software development needs. We do our best to make good applications on gaming, web, mobile or desktop applications, utilizing the latest technology trends.</p>
        </div>

        <div class="row">
            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in">
                <div class="icon-box icon-box-pink">
                    <div class="icon"><i class="bx bx-paint"></i></div>
                    <h4 class="title"><a href="@Url.Action("MobileAppDevelopment", "MobileApp")" class="text-primary">Mobile App Development</a></h4>
                    <p class="description">We bring your unique ideas to life with our expertise in developing visually stunning and interactive applications.</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="100">
                <div class="icon-box icon-box-cyan">
                    <div class="icon"><i class="bx bx-code"></i></div>
                    <h4 class="title"><a href="@Url.Action("WebDevelopment", "Web")" class="text-primary">Web Development</a></h4>
                    <p class="description">We also offer web develeopment solutions to our partners and customers so that they can sell, display or promote their efforts and products through web.</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
                <div class="icon-box icon-box-green">
                    <div class="icon"><i class="bx bx-game"></i></div>
                    <h4 class="title"><a href="@Url.Action("GameDevelopment", "Game")" class="text-primary">Game Development</a></h4>
                    <p class="description">We offer game development solutions to our customers and make our own indie games for showcasing.</p>
                </div>
            </div>

            <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="300">
                <div class="icon-box icon-box-blue">
                    <div class="icon"><i class="bx bx-wrench"></i></div>
                    <h4 class="title"><a href="@Url.Action("DesktopDevelopment", "Desk")" class="text-primary">Desktop Development</a></h4>
                    <p class="description">We create desktop applications that solves either real life problems or keep up with a corporate solution.</p>
                </div>
            </div>

        </div>

    </div>
</section>
<!-- End Services Section -->


<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio">
    <div class="container">

        <div class="section-title" data-aos="fade-up">
            <h2>Portfolio</h2>
            <p>List of our works is given below. Details can be accessed through development page or by going to connection on the image.</p>
        </div>

        <div class="row">
            <div class="col-lg-12 d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
                <ul id="portfolio-flters">
                    <li data-filter="*" class="filter-active">All</li>
                    <li data-filter=".filter-game">Games</li>
                    <li data-filter=".filter-mobile">MobileApps</li>
                    <li data-filter=".filter-web">WebApps</li>
                    <li data-filter=".filter-desk">DesktopApps</li>
                </ul>
            </div>
        </div>

        <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
            @foreach (var item in Model.GameQuickViewModels)
            {
                <div class="col-lg-4 col-md-6 portfolio-item filter-app filter-game">
                    <div class="portfolio-wrap">
                        @if (item.Thumbnails.Count > 0)
                        {
                            <img src="@Url.Content(item.Thumbnails[0])" class="img-fluid" alt="">
                        }
                        else
                        {
                            <img src="~/assets/img/portfolio/27230.jpg" class="img-fluid" alt="Placeholder">
                        }
                        <div class="portfolio-info">
                            <h4>@item.ProjectName</h4>
                        </div>
                        <div class="portfolio-links">
                            @if (item.Thumbnails.Count > 0)
                            {
                                <a href="@Url.Content(item.Thumbnails[0])" data-gallery="portfolioGallery" class="portfolio-lightbox" title="@item.ProjectName"><i class="bx bx-plus"></i></a>
                            }
                            <a href="@Url.Action("GameDevelopment", "Game", new { searchedTag = item.ProjectName })" title="More Details" title="More Details"><i class="bx bx-link"></i></a>
                        </div>
                    </div>
                </div>
            }


            @foreach (var item in Model.WebQuickViewModels)
            {
                <div class="col-lg-4 col-md-6 portfolio-item filter-app filter-web">
                    <div class="portfolio-wrap">
                        @if (item.Thumbnails.Count > 0)
                        {
                            <img src="@Url.Content(item.Thumbnails[0])" class="img-fluid" alt="">
                        }
                        else
                        {
                            <img src="~/assets/img/portfolio/27230.jpg" class="img-fluid" alt="Placeholder">
                        }
                        <div class="portfolio-info">
                            <h4>@item.ProjectName</h4>
                        </div>
                        <div class="portfolio-links">
                            @if (item.Thumbnails.Count > 0)
                            {
                                <a href="@Url.Content(item.Thumbnails[0])" data-gallery="portfolioGallery" class="portfolio-lightbox" title="@item.ProjectName"><i class="bx bx-plus"></i></a>
                            }
                            <a href="@Url.Action("WebDevelopment", "Web", new { searchedTag = item.ProjectName })" title="More Details"><i class="bx bx-link"></i></a>
                        </div>
                    </div>
                </div>
            }

            @foreach (var item in Model.MobileAppQuickViewModels)
            {
                <div class="col-lg-4 col-md-6 portfolio-item filter-app filter-mobile">
                    <div class="portfolio-wrap">
                        @if (item.Thumbnails.Count > 0)
                        {
                            <img src="@Url.Content(item.Thumbnails[0])" class="img-fluid" alt="">
                        }
                        else
                        {
                            <img src="~/assets/img/portfolio/27230.jpg" class="img-fluid" alt="Placeholder">
                        }
                        <div class="portfolio-info">
                            <h4>@item.ProjectName</h4>
                        </div>
                        <div class="portfolio-links">
                            @if (item.Thumbnails.Count > 0)
                            {
                                <a href="@Url.Content(item.Thumbnails[0])" data-gallery="portfolioGallery" class="portfolio-lightbox" title="@item.ProjectName"><i class="bx bx-plus"></i></a>
                            }
                            <a href="@Url.Action("MobileAppDevelopment", "MobileApp", new { searchedTag = item.ProjectName })" title="More Details"><i class="bx bx-link"></i></a>
                        </div>
                    </div>
                </div>
            }

            @foreach (var item in Model.DesktopQuickViewModels)
            {
                <div class="col-lg-4 col-md-6 portfolio-item filter-app filter-desk">
                    <div class="portfolio-wrap">
                        @if (item.Thumbnails.Count > 0)
                        {
                            <img src="@Url.Content(item.Thumbnails[0])" class="img-fluid" alt="">
                        }
                        else
                        {
                            <img src="~/assets/img/portfolio/27230.jpg" class="img-fluid" alt="Placeholder">
                        }
                        <div class="portfolio-info">
                            <h4>@item.ProjectName</h4>
                        </div>
                        <div class="portfolio-links">
                            @if (item.Thumbnails.Count > 0)
                            {
                                <a href="@Url.Content(item.Thumbnails[0])" data-gallery="portfolioGallery" class="portfolio-lightbox" title="@item.ProjectName"><i class="bx bx-plus"></i></a>
                            }
                            <a href="@Url.Action("DesktopDevelopment", "Desk", new { searchedTag = item.ProjectName })" title="More Details"><i class="bx bx-link"></i></a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    </section><!-- End Portfolio Section -->

    <!-- ======= Clients Section ======= -->
    @*<section id="clients" class="clients">
        <div class="container">

            <div class="section-title" data-aos="fade-up">
                <h2>Clients</h2>
                <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit sint consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea. Quia fugiat sit in iste officiis commodi quidem hic quas.</p>
            </div>

            <div class="row no-gutters clients-wrap clearfix wow fadeInUp">

                <div class="col-lg-3 col-md-4 col-xs-6">
                    <div class="client-logo" data-aos="zoom-in">
                        <img src="~/assets/img/clients/client-1.png" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-lg-3 col-md-4 col-xs-6">
                    <div class="client-logo" data-aos="zoom-in" data-aos-delay="100">
                        <img src="~/assets/img/clients/client-2.png" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-lg-3 col-md-4 col-xs-6">
                    <div class="client-logo" data-aos="zoom-in" data-aos-delay="150">
                        <img src="~/assets/img/clients/client-3.png" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-lg-3 col-md-4 col-xs-6">
                    <div class="client-logo" data-aos="zoom-in" data-aos-delay="200">
                        <img src="~/assets/img/clients/client-4.png" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-lg-3 col-md-4 col-xs-6">
                    <div class="client-logo" data-aos="zoom-in" data-aos-delay="250">
                        <img src="~/assets/img/clients/client-5.png" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-lg-3 col-md-4 col-xs-6">
                    <div class="client-logo" data-aos="zoom-in" data-aos-delay="300">
                        <img src="~/assets/img/clients/client-6.png" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-lg-3 col-md-4 col-xs-6">
                    <div class="client-logo" data-aos="zoom-in" data-aos-delay="350">
                        <img src="~/assets/img/clients/client-7.png" class="img-fluid" alt="">
                    </div>
                </div>

                <div class="col-lg-3 col-md-4 col-xs-6" data-aos="zoom-in" data-aos-delay="400">
                    <div class="client-logo">
                        <img src="~/assets/img/clients/client-8.png" class="img-fluid" alt="">
                    </div>
                </div>

            </div>

        </div>
    </section><!-- End Clients Section -->*@

</main>
<!-- End #main -->